export const DISPLAY_ALERT = "SHOW_ALERT";

export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_TICKET_BEGIN = "CREATE_TICKET_BEGIN";
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_ERROR = "CREATE_TICKET_ERROR";

export const GET_TICKET_BEGIN = "GET_TICKET_BEGIN";
export const GET_TICKET_SUCCESS = "GET_TICKET_SUCCESS";

export const SET_EDIT_TICKET = "SET_EDIT_TICKET";

export const DELETE_TICKET_BEGIN = "DELETE_TICKET_BEGIN";

export const EDIT_TICKET_BEGIN = "EDIT_TICKET_BEGIN";
export const EDIT_TICKET_SUCCESS = "EDIT_TICKET_SUCCESS";
export const EDIT_TICKET_ERROR = "EDIT_TICKET_ERROR";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const GET_COMMENTS_BEGIN = "GET_COMMENTS_BEGIN";

export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";

export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const CREATE_COMMENT_BEGIN = "CREATE_COMMENT_BEGIN";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_ERROR = "CREATE_COMMENT_ERROR";

export const SET_EDIT_COMMENT = "SET_EDIT_COMMENT";

export const DELETE_COMMENT_BEGIN = "DELETE_COMMENT_BEGIN";

export const EDIT_COMMENT_BEGIN = "EDIT_COMMENT_BEGIN";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const EDIT_COMMENT_ERROR = "EDIT_COMMENT_ERROR";

export const CLEAR_VALUES_COMMENT = "CLEAR_VALUES_COMMENT";
